# Generated by Django 5.0.3 on 2024-03-24 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_task_options_task_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='completion_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
